name = "Xoodyak-384-DOM1-v1"
description = "Xoodyak with 1st order masking"
author = ["Richard Haeussler", "Abubakr Abdulgadir"]
url = "https://github.com/GMUCERG/Xoodyak-SCA"
license = "GPL-3.0"
version = "0.2.0"

[rtl]
sources = [
    "src_rtl/LWC_config.vhd",
    "src_rtl/LWC_rtl/NIST_LWAPI_pkg.vhd",
    "src_rtl/design_pkg.vhd",
    "src_rtl/xoodyak_constants.vhd",
    "src_rtl/lambda.vhd",
    "src_rtl/and_dom_n.vhd",
    "src_rtl/chi384.vhd",
    "src_rtl/rho_east.vhd",
    "src_rtl/xoodoo_round_pr.vhd",
    "src_rtl/cyclist_ops.vhd",
    "src_rtl/xoodyak_dp.vhd",
    "src_rtl/xoodyak_ctrl.vhd",
    "src_rtl/CryptoCore.vhd",
    "src_rtl/LWC_rtl/FIFO.vhd",
    "src_rtl/LWC_rtl/key_piso.vhd",
    "src_rtl/LWC_rtl/data_piso.vhd",
    "src_rtl/LWC_rtl/PreProcessor.vhd",
    "src_rtl/LWC_rtl/data_sipo.vhd",
    "src_rtl/LWC_rtl/PostProcessor.vhd",
    "src_rtl/LWC_rtl/LWC_SCA.vhd",
]
# includes = []
top = "LWC_SCA"
clock.port = "clk"
# clock.port = "clk"
# reset.port = "reset"
# reset.active_high = true
# reset.asynchronous = false
# parameters = { G_GENERIC1 = 123 }

[language]
vhdl.version = "2008"
# vhdl.synopsys = false
# verilog.version = "2001"
# systemverilog.version = "2009"

[tb]
sources = ["src_tb/LWC_TB_SCA.vhd"]
top = "LWC_TB"
# includes = []

[tb.parameters]
# {file: "xx"} is an extension to specify a string generic/parameter pointing to a relative path:
G_FNAME_PDI = { file = "KAT/Xoodyak-384-DOM1-v1/pdi_shared_2.txt" }
G_FNAME_SDI = { file = "KAT/Xoodyak-384-DOM1-v1/sdi_shared_2.txt" }
G_FNAME_RDI = { file = "KAT/Xoodyak-384-DOM1-v1/rdi.txt" }
G_FNAME_DO = { file = "KAT/Xoodyak-384-DOM1-v1/do.txt" }
G_TEST_MODE = 0 # 1: stall inputs and outputs
G_RANDOM_STALL = true
G_TIMEOUT_CYCLES = 1000
G_MAX_FAILURES = 0

[lwc.aead]
algorithm = "xoodyak128"
# key_bits = 128
# npub_bits = 128
# tag_bits = 128
# input_sequence.encrypt = [ "npub", "ad", "pt", "tag" ]
# input_sequence.decrypt = [ "npub", "ad", "ct", "tag" ]

# [lwc.hash]
# algorithm = "" ###### (hashing is not supported)
# digest_bits = 128

[lwc.ports]
# pdi.bit_width = 32
pdi.num_shares = 2
rdi.bit_width = 384
# sdi.bit_width = 32
sdi.num_shares = 2

[lwc.sca_protection]
target = ["timing", "sda", "dpa"]
order = 1
